#!/usr/bin/env bash
# Generates a MySQL dump & creates a compressed archive out of it
if [ $# -gt 0 ]; then
        mysqldump -u root -p "$1" --all-databases --result-file=backup.sql
        date=$(date +%d-%m-%Y)
        tar -czf "$date.tar.gz" backup.sql
fi
